### ISSUE TITLE
Recive data from POST request body, not meta

### ISSUE THREAD

**Issue by ms0ur** [404-hackaton/hackaton_backend#1]
В файле base/views.py вы получаете данные при регистрации из заголовков.
Во первых правильнее получать данные из тела POST запроса, особенно данные типа пароля, поскольку данны в теле запроса шифруются через ssl, а заголовки не всегда.
К тому же с телом запроса проще работать на фронте
Надеюсь на ваше понимание дорогой бэкенд

**Comment by ms0ur** [comment]
вроде миха поправил в 3e3f6a4, но протести @Jeno7u

**Comment by Jeno7u** [comment]
I unserstand your issue, my work partner who worked in this field will resolve it.

**Comment by Jeno7u** [comment]
Ну какие вопросы тогда, епта

**Comment by ms0ur** [comment]
ну протести вдруг все поломалось от этого

**Comment by Jeno7u** [comment]
Окей, прийду протестирую через postman
